"""
build_colab.py
--------------
Generates colab/regime_detection_colab.py: one self-contained file to paste
into a single Google Colab cell. It embeds the current sources of
gpu_regimes.py, regime_identification.py and validate_gpu_regimes.py, so the
Colab run uses exactly the code in this repository.

    python src/build_colab.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
MODULES = ['gpu_regimes.py', 'regime_identification.py', 'validate_gpu_regimes.py']
TARGET = os.path.join(HERE, '..', 'colab', 'regime_detection_colab.py')

TEMPLATE = '''# =============================================================================
# Regime identification: full run on a Google Colab GPU. Paste this whole file
# into ONE Colab cell and run it.
#
# 1. Runtime > Change runtime type > GPU (T4 or better) > Save.
# 2. Paste this file into a cell and run it. Allow Google Drive access when
#    asked; results and checkpoints are saved to MyDrive/regime_detection so a
#    disconnect does not lose finished work. If the runtime disconnects, run
#    the cell again: finished simulation blocks are loaded from the checkpoints.
# 3. At the end a zip with everything (RESULTS.md, CSV tables, figures,
#    summary.json, the code and package versions) downloads automatically and
#    the scorecard is printed below.
#
# Set QUICK_TEST = True for a ~10 minute smoke test first if you like.
# Generated by src/build_colab.py from the repository sources; do not edit the
# embedded modules by hand.
# =============================================================================

QUICK_TEST = False   # True: 1990-2025, 2 replications (checks that everything runs; not for the paper)
N_SIM = 100          # simulation replications per data-generating process
N_PELT = 25          # replications per process that also get the (CPU-only) PELT change-point method
SAVE_TO_DRIVE = True

import os, sys, subprocess, shutil, time, importlib

subprocess.run([sys.executable, '-m', 'pip', 'install', '-q',
                'ruptures', 'arch', 'jumpmodels', 'hmmlearn', 'yfinance'], check=True)
import torch
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
else:
    print('WARNING: no GPU. Runtime > Change runtime type > GPU, then run again. Continuing on the CPU (slow).')

BASE = '/content'
if SAVE_TO_DRIVE:
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        BASE = '/content/drive/MyDrive'
    except Exception as e:
        print('Google Drive not mounted, saving to /content instead:', e)
WORK = os.path.join(BASE, 'regime_detection')
OUT = os.path.join(WORK, 'results_quick' if QUICK_TEST else 'results')
DATA = os.path.join(WORK, 'data')
SRC = '/content/regime_src'
os.makedirs(SRC, exist_ok=True)

SOURCES = {
%(sources)s
}
for name, code in SOURCES.items():
    with open(os.path.join(SRC, name), 'w', encoding='utf-8') as f:
        f.write(code)
if SRC not in sys.path:
    sys.path.insert(0, SRC)
# parallel PELT worker processes must also find the modules
os.environ['PYTHONPATH'] = SRC + (os.pathsep + os.environ['PYTHONPATH'] if os.environ.get('PYTHONPATH') else '')
for m in ('gpu_regimes', 'regime_identification', 'validate_gpu_regimes'):
    sys.modules.pop(m, None)
import regime_identification as R

args = ['--validate', '--out', OUT, '--data-dir', DATA, '--n-sim', str(N_SIM), '--n-pelt', str(N_PELT)]
if QUICK_TEST:
    args.append('--quick')
R.main(args)

# Reproducibility bundle: code, package versions, data snapshot
os.makedirs(os.path.join(OUT, 'code'), exist_ok=True)
for name in SOURCES:
    shutil.copy(os.path.join(SRC, name), os.path.join(OUT, 'code', name))
snap = os.path.join(DATA, 'regime_data_snapshot.txt')
if os.path.exists(snap):
    shutil.copy(snap, os.path.join(OUT, 'regime_data_snapshot.txt'))
from importlib.metadata import version
pkgs = ['torch', 'numpy', 'pandas', 'scipy', 'scikit-learn', 'arch', 'ruptures', 'jumpmodels', 'hmmlearn', 'yfinance']
with open(os.path.join(OUT, 'environment.txt'), 'w') as f:
    f.write(f'python {sys.version.split()[0]}\\n')
    f.write(f'device {torch.cuda.get_device_name(0) if torch.cuda.is_available() else "cpu"}\\n')
    for p in pkgs:
        try:
            f.write(f'{p} {version(p)}\\n')
        except Exception:
            pass
zip_path = shutil.make_archive(os.path.join('/content', 'regime_results_quick' if QUICK_TEST else 'regime_results'),
                               'zip', OUT)
print('\\nResults folder:', OUT)
print('Zip:', zip_path)
try:
    import pandas as pd
    from IPython.display import display, Markdown
    display(Markdown('### Scorecard'))
    display(pd.read_csv(os.path.join(OUT, 'S_scorecard.csv')))
    from google.colab import files
    files.download(zip_path)
except Exception as e:
    print('Automatic download unavailable (%%s); download the zip from the Files panel.' %% e)
'''


def main():
    parts = []
    for name in MODULES:
        with open(os.path.join(HERE, name), encoding='utf-8') as f:
            parts.append(f'    {name!r}: {f.read()!r},')
    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, 'w', encoding='utf-8') as f:
        f.write(TEMPLATE % {'sources': '\n'.join(parts)})
    print('wrote', os.path.normpath(TARGET))


if __name__ == '__main__':
    main()
